openapi: 3.0.1
info:
  title: API_An_Api_Returns_404
  description: API Definition of API_An_Api_Returns_404
  version: 1.0.0
servers:
- url: http://localhost:8290/api/v2/not-found
paths:
  /:
    get:
      responses:
        default:
          description: Default response
