openapi: 3.0.1
info:
  title: API_An_Api_Make_Switch_After_Calling_External_APi
  description: API Definition of API_An_Api_Make_Switch_After_Calling_External_APi
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integrations/switch-cases
paths:
  /:
    get:
      responses:
        default:
          description: Default response
