openapi: 3.0.1
info:
  title: Continents
  description: API Definition of Continents
  version: 1.0.0
servers:
- url: http://localhost:8290/continents
paths:
  /:
    get:
      responses:
        default:
          description: Default response
