openapi: 3.0.1
info:
  title: API_Get_Student_Dummy_Data
  description: API Definition of API_Get_Student_Dummy_Data
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integrations/students/static-data
paths:
  /:
    get:
      responses:
        default:
          description: Default response
