openapi: 3.0.1
info:
  title: API_Integration_Call
  description: API Definition of API_Integration_Call
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integrations/students/real-integration-endpoint
paths:
  /:
    get:
      responses:
        default:
          description: Default response
