openapi: 3.0.1
info:
  title: FindPostsWithItsCommentsAPI
  description: API Definition of FindPostsWithItsCommentsAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/posts/commenst
paths:
  /:
    get:
      responses:
        default:
          description: Default response
