openapi: 3.0.1
info:
  title: JsonPlaceHolderIntegrationAPIV2
  description: API Definition of JsonPlaceHolderIntegrationAPIV2
  version: 1.0.0
servers:
- url: http://localhost:8290/json-placeholder/with-clone-and-aggregate-example/v2
paths:
  /:
    get:
      responses:
        default:
          description: Default response
