openapi: 3.0.1
info:
  title: API_GetRandomJsonObject
  description: API Definition of API_GetRandomJsonObject
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integration/scheduled-tasks/users
paths:
  /:
    get:
      responses:
        default:
          description: Default response
