openapi: 3.0.1
info:
  title: Reading_JsonPlaceHolderUrlFromPropertiesFile_Api
  description: API Definition of Reading_JsonPlaceHolderUrlFromPropertiesFile_Api
  version: 1.0.0
servers:
- url: http://localhost:8290/integrations/wso2/json-placeholder
paths:
  /:
    get:
      responses:
        default:
          description: Default response
