openapi: 3.0.1
info:
  title: API_GetAllPosts
  description: API Definition of API_GetAllPosts
  version: 1.0.0
servers:
- url: http://localhost:8290/integrations/wso2/json-placeholder/posts
paths:
  /:
    get:
      responses:
        default:
          description: Default response
