openapi: 3.0.1
info:
  title: GetAllPosts
  description: API Definition of GetAllPosts
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integration/posts
paths:
  /:
    get:
      responses:
        default:
          description: Default response
