openapi: 3.0.1
info:
  title: API_GetAllUsers_With_Caching
  description: API Definition of API_GetAllUsers_With_Caching
  version: '1'
servers:
- url: http://localhost:8290/wso2/integrations/caching/users
paths:
  /:
    get:
      responses:
        default:
          description: Default response
