openapi: 3.0.1
info:
  title: API_WSO2_Official_Cache_Example
  description: API Definition of API_WSO2_Official_Cache_Example
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/official/docs/example/cache
paths:
  /:
    get:
      responses:
        default:
          description: Default response
