openapi: 3.0.1
info:
  title: Actors_API
  description: API Definition of Actors_API
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/actors
paths:
  /:
    get:
      responses:
        default:
          description: Default response
