openapi: 3.0.1
info:
  title: CityInformationAPI
  description: API Definition of CityInformationAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/city
paths:
  /lookup/{zipCode}:
    get:
      parameters:
      - name: zipCode
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
