openapi: 3.0.1
info:
  title: API_Employee
  description: API Definition of API_Employee
  version: 1.0.0
servers:
- url: http://localhost:8290/wso2/integrations/employee
paths:
  /:
    get:
      responses:
        default:
          description: Default response
